name: Publish Ruby gem to RubyGems

on:
  push:
    tags:
      - 'ruby-v*'

jobs:
  publish:
    name: Publish nzdata gem to RubyGems
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1.327.0
        with:
          ruby-version: '4.0'
      - name: Build gem
        run: cd ruby && gem build nzdata.gemspec
      - name: Push gem
        run: cd ruby && gem push nzdata-*.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
